POSTGRES:
    CREDENTIALS_PATH: 'C:\Users\pavel\PycharmProjects\UIR\model_code\settings\pstgrs.yml'

TABLENAMES_POSTGRES:
    data: 'uir.data'
    predicts: 'uir.predicts'

PATHS:
    SCRIPTS_PATH: 'C:\Users\pavel\PycharmProjects\UIR\model_code\sql'
    DATA_PATH: 'C:\Users\pavel\PycharmProjects\UIR\data'
    TEMPLATE_PATH: 'C:\Users\pavel\PycharmProjects\UIR\model_code\templates'
    HTML_GRAPHICS_PATH: 'C:\Users\pavel\PycharmProjects\UIR\model_code\html_graphics'

MODEL:
    model_file: